### PR TITLE
New project system & Cargo based build system

### LINKED ISSUE #223: Consider moving to VS Common Project System
This seems to be the future. See https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/intro.md, especially the section _Is CPS right for me?_

[R Tools for VS](https://github.com/Microsoft/RTVS) seems to be using this, as a reference.

### LINKED ISSUE #232: Provide a ProjectGenerator to be able to open Cargo.toml directly
This can be done with a custom `RegistrationAttribute`.

Compare https://github.com/Microsoft/RTVS/blob/master/src/ProjectSystem/Impl/Package/Registration/ProvideProjectFileGeneratorAttribute.cs

`FileNames` should be `Cargo.toml`, `FileExtensions` should be empty.

### PR DESCRIPTION
**Pull request by Boddlnagg**
The Good:
- The build system has been rewritten to be based on Cargo (requires a `Cargo.toml` and calls `cargo build` internally).
- You can now directly open `Cargo.toml` files and the solution explorer will show all the files in the respective directory (except for some filtered things, such as the `target` folder). VS will still create a `.rsproj` file, but it only contains some user settings.
- Project System is based on [CPS](https://github.com/Microsoft/VSProjectSystem) and mirrors the file system. No need for fragile module parsing to find included source files. CPS has many advantages over the old project system: Most of the code is shipped and updated with VS; it is ["designed from the ground up to be performant, scalable, and responsive"](https://blogs.msdn.microsoft.com/visualstudio/2015/06/02/introducing-the-project-system-extensibility-preview/); documentation is a bit lacking, but going to improve, since CPS is used by the C# and VB project system in VS "15". The project *Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring* together with its dependency *Microsoft.Common.Core* has been imported from [RTVS](https://github.com/Microsoft/RTVS).
- This fixes #223, #232, #195, #119, #118, #113, #214 and #215

The Bad:
- Support for VS2013 is dropped, because the new project system doesn't support it
- Many old tests have been removed, and I have not yet written new tests (but integration tests were disabled on CI anyway and should probably be redesigned to work on AppVeyor)
- Error markers (squiggly lines) are currently not shown. I haven't been able to figure out why.
- The parsing of compiler messages is based on https://github.com/rust-lang/cargo/pull/3000 and requires a recent nightly, which will hit stable in December (but this is the only way that `cargo build` output which includes dependencies can be reliably captured and parsed)
- `.rsproj` projects created with previous versions of VisualRust are completely incompatible with this new version

The Rest:
- Updated to require .NET 4.6 (allows us to use C# 6 features and was necessary because RTVS uses it)
- Updated most projects to use project.json for NuGet packages (easier to maintain)

### CODE REVIEW

**Comment by downtime0** [comment]
This is a great change for the project and outweighs the loss of VS2013 support.

Great job to those involved.

**Comment by Boddlnagg** [comment]
@vosen: It would be nice if you could comment what you think about this.

Otherwise, if no one has any objections, I'm going to merge in a few days.

**Comment by Vbif** [comment]
Is visit_toml.dll and all Manifest stuff from Cargo project still needed?

**Comment by Boddlnagg** [comment]
No, it's currently unused. What's implemented in the PR is only reading the manifest using `cargo manifest`. As soon as we want to edit the manifest from the UI, we will need some way to parse and edit the TOML file directly, without reformatting everything (i.e. preserving comments and whitespace, etc). That's what vist_toml.dll is built for, but it's unfinished and not really documented. We need to decide what will be done there, but it's out of scope for this PR.

**Comment by vosen** [comment]
The idea of moving us to CPS is sound and is something that I wanted to do.
The problem was always that would have required a lot of effort to port: redoing stuff with MEF and .xaml rules is time consuming and even things like .pkgdef are extremely fiddly.
This commit pretty forces my hand in this regard.
While I'm not 100% enthusiast of removing tests and I see that some thing are broken (.rsproj loading, probably due to aforementioned pkgdef, tested on a clean machine) I'm Ok with the commit. Someone had to do it, sooner or later.

**Pull request merged**
